apiVersion: 1

datasources:
  - name: PostgreSQL-Joomla
    type: postgres
    access: proxy
    url: database:5432
    user: joomlauser
    secureJsonData:
      password: joomlapassword
    jsonData:
      database: joomladb
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
    isDefault: true
    editable: false
